### ISSUE TITLE
Pass mimeType option not working

### ISSUE THREAD

**Issue by dattm97** [samuelweckstrom/react-record-webcam#11]
I try pass mimeType to options props is "video/mp4" but the output is always "video/x-matroska;codecs=avc1,opus".
Seems mimeType option is not working.

**Comment by aLx450** [comment]
Same goes for the sizing props, unless they work for you.... if you set a maxHeight in that options object, it will not apply.

**Comment by samuelweckstrom** [comment]
Thanks for the feedback! Will have a look today.

**Comment by samuelweckstrom** [comment]
@dattm97 @aLx450 I've update the package with a new version - please have a look at the updated [Codesandbox demo](https://codesandbox.io/s/react-record-webcam-demo-zog8c).

I've refactored the code a bit so there are some breaking changes but nothing too bad. Nonetheless passing the `filetype` should set the mimeType now accordingly, as well as setting the width and height  should work too now!
