### ISSUE TITLE
NPM Dependency error

### ISSUE THREAD

**Issue by cgordon5025** [samuelweckstrom/react-record-webcam#41]
I was using this the other week, and it was fine. Now working on a new project I tried downloading it, and it states that there is a dependency error.

`npm ERR! code ERESOLVE 
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-record-webcam@0.0.18
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@"^18.0.0" from @testing-library/react@13.4.0
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^13.4.0" from the root project
npm ERR!   4 more (react-dom, react-router, react-router-dom, react-scripts)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3" from react-record-webcam@0.0.18
npm ERR! node_modules/react-record-webcam
npm ERR!   react-record-webcam@"^0.0.18" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.3" from react-record-webcam@0.0.18
npm ERR!   node_modules/react-record-webcam
npm ERR!     react-record-webcam@"^0.0.18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/example/.npm/eresolve-report.txt for a full report.`

Feels like it should be fine since all the dependency is asking for is any version of react newer than 16.3, but I might be missing something here. Any help would be greatly appreciated

**Comment by samuelweckstrom** [comment]
Dependencies updated in #46. Closing.
