### ISSUE TITLE
Edit Webcam Recorder

### ISSUE THREAD

**Issue by tytyhensley** [samuelweckstrom/react-record-webcam#6]
Hi, 
I was wondering is there any possible way to edit the size of the webcam itself and have audio on for the playback clips
Thank you

**Comment by samuelweckstrom** [comment]
You can pass options to the hook and set the size of the outputted video there, or then via CSS if you just want the preview to be larger. You can check the [CodeSandbox](https://codesandbox.io/s/react-record-webcam-demo-zog8c) demo and play around with the files there to see if you get the result you want.
