### ISSUE TITLE
Getting recorded video object

### ISSUE THREAD

**Issue by iltertaha** [samuelweckstrom/react-record-webcam#7]
Hi, thanks for this great package. 
I want to access to the recorded video in order to upload to my webserver. But I couldn't figure out how to get recorded video object. Can you give me an example?

Thanks.

**Comment by n4beel** [comment]
Hello, This is for sure a great library, my team also missed this functionality, therefore we updated the library's hook version and added one more function to it with name `getFile`, I'll make a PR for getting it added to this library

**Comment by martimarkov** [comment]
@n4beel Hey would you be able to make the PR?

**Comment by samuelweckstrom** [comment]
@iltertaha @n4beel @martimarkov 

Hey guys sorry I've been too busy with work to attend to this package. I've updated the version and theres now a `getRecording` function you can run from the hook to get the recording blob, which you can then send over to whatever API you have. 

I've updated the [CodeSandbox](https://codesandbox.io/s/react-record-webcam-demo-zog8c) URL with examples for both hooks and render props.
