### ISSUE TITLE
Fix MediaRecorder is not defined on SSR

### ISSUE THREAD

**Issue by phamthainb** [samuelweckstrom/react-record-webcam#79]
When i using with SSR, I got this error.
```
[1] ReferenceError: MediaRecorder is not defined
[1]     at /Users/xxx/video_recorder/codec.ts:63:5
[1]     at Array.forEach (<anonymous>)
[1]     at containers.reduce.mimeType (/Users/xx/video_recorder/codec.ts:61:11)
```
So, in the codec.ts should add check `typeof MediaRecorder !== 'undefined'`
Thanks

**Comment by SilvusTV** [comment]
i'm using AdonisJS with react and yeah... Same error. but i really don't know how to fix it...

**Comment by phamthainb** [comment]
> i'm using AdonisJS with react and yeah... Same error. but i really don't know how to fix it...

Hi, You can check `typeof MediaRecorder !== 'undefined'` before any where using `MediaRecorder`.

**Comment by SilvusTV** [comment]
> > i'm using AdonisJS with react and yeah... Same error. but i really don't know how to fix it...
> 
> Hi, You can check `typeof MediaRecorder !== 'undefined'` before any where using `MediaRecorder`.

The problem is, i never use MediaRecorder. i just import like in the documentation : 
  `const { createRecording, openCamera, startRecording, stopRecording } = useRecordWebcam()`
and this line ↑ create error.
Sooo i don't really undertsand...

**Comment by phamthainb** [comment]
> > > i'm using AdonisJS with react and yeah... Same error. but i really don't know how to fix it...
> > 
> > 
> > Hi, You can check `typeof MediaRecorder !== 'undefined'` before any where using `MediaRecorder`.
> 
> The problem is, i never use MediaRecorder. i just import like in the documentation : `const { createRecording, openCamera, startRecording, stopRecording } = useRecordWebcam()` and this line ↑ create error. Sooo i don't really undertsand...

Just take a look, The problem is not fixed on the lib, so when you using lib you will got this error.
You can 2 way below:
1. Using [patch-package](https://www.npmjs.com/package/patch-package) for edit code 
2. Copy all file of this package and make it on to you code ( I chose this way )
<img width="1260" alt="image" src="https://github.com/samuelweckstrom/react-record-webcam/assets/55950535/eac7b7f2-6a32-4a4e-85a7-2c34ca1d0c81">

**Comment by SilvusTV** [comment]
Merci beaucoup ! !! je vais essayer d'utiliser la première méthode. Seulement, je ne trouve pas le bon fichier... (i'm a beginner with node sorry )

**Comment by samuelweckstrom** [comment]
@phamthainb Thanks for the issue, will create a patch for this!
