### ISSUE TITLE
MediaRecorder is not defined

### ISSUE THREAD

**Issue by SilvusTV** [samuelweckstrom/react-record-webcam#82]
i've seen a similar error patched recently but i'm still having a problem. i've run quite a few different tests but this time, just by copying the demo code, it doesn't work and this error appears. I can't find a solution. As long as `= useRecordWebcam()` is in the code, it won't start with this error...
   ReferenceError: MediaRecorder is not defined
![image](https://github.com/samuelweckstrom/react-record-webcam/assets/63901024/3fb4091e-57ea-427f-8731-399d3317c0e5)

**Comment by samuelweckstrom** [comment]
Which version of the package are you using? The latest version on the Stackblitz link should work just fine. Maybe you have a issue with permissions in your browser?

**Comment by SilvusTV** [comment]
> Which version of the package are you using? The latest version on the Stackblitz link should work just fine. Maybe you have a issue with permissions in your browser?

Well, I'm using the last version (1.1.3) and I don't think it's my browser because this error come on the startup project. So before I go on my browser

**Comment by samuelweckstrom** [comment]
I cant unfortunately debug this on your machine. You will have to share some more information, or even better try to find the reason why this is not working and maybe contribute a fix if there is a bug :)

**Comment by SilvusTV** [comment]
> I cant unfortunately debug this on your machine. You will have to share some more information, or even better try to find the reason why this is not working and maybe contribute a fix if there is a bug :)

Well thanks for your response. i will see if i can debug this. and i let you know here !

**Comment by NimBuzz01** [comment]
Even though it is the latest version (1.1.3) the package didn't seem to have updated.

![Screenshot 2024-03-21 094315](https://github.com/samuelweckstrom/react-record-webcam/assets/86093827/353a631c-58f0-42fb-a469-35afd4cd7db8)

**Comment by samuelweckstrom** [comment]
Ah yeah I see now the latest version didn't pick up all the changes. Sorry! I've published 1.1.4, which should include the checks for `MediaRecorder`.
