### ISSUE TITLE
Example of Camera Mode Switcher for Toggling Between Front and Back Cameras

### ISSUE THREAD

**Issue by jjppsia** [samuelweckstrom/react-record-webcam#84]
I am attempting to develop a mobile camera mode switcher that allows the user to toggle between the front and back cameras. Here’s an example from React Webcam: https://codepen.io/mozmorris/pen/mddvKBE.

I tried to set the mediaTrackConstraints to environment to see if it uses the back camera but it still uses the default camera which is the front camera

**Comment by samuelweckstrom** [comment]
The library was written for multi camera setups, and there is currently no way to "hot-swap" cameras for a single recording instance. So on mobile you will have to create separate recording instances for each input device (front and back camera).
